import { CategorisedOption, selectValuesFromWeightedCategorisedOptions } from "../generatorUtils";

export function generateBond() {
  return selectValuesFromWeightedCategorisedOptions(bondOptions);
}

export const bondOptions: CategorisedOption[] = [
  { category: "", subCategory: "", instance: "I would die to recover an ancient artifact of my faith that was lost long ago.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I owe me life to the priest who took me in when my parents died.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Everything I do is for the common people.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will do anything to protect the temple where I served.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I owe everything to my mentor--a horrible person who's probably rotting in jail somewhere.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Somewhere out there I have a child who doesn't know me. I'm making the world better for him or her.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "A powerful person killed someone I love. Some day soon, I'll have my revenge.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm trying to pay off an old debt I owe to a generous benefactor.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My ill-gotten gains go to support my family.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Something important was taken from me, and I aim to steal it back.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will become the greatest thief that ever lived.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm guilty of a terrible crime. I hope I can redeem myself for it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Someone I loved died because of a mistake I made. That will never happen again.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My instrument is my most treasured possession, and it reminds me of someone I love.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Someone stole my precious instrument, and someday I'll get it back.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I want to be famous, whatever it takes.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I idolize a hero of the old tales and measure my deeds against that person's.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will do anything to prove myself superior to me hated rival.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I would do anything for the other members of my old troupe.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a family, but I have no idea where they are. One day, I hope to see them again.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I worked the land, I love the land, and I will protect the land.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My tools are symbols of my past life, and I carry them so that I will never forget my roots.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I protect those who cannot protect themselves.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I wish my childhood sweetheart had come with me to pursue my destiny.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The workshop where I learned my trade is the most important place in the world to me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy. ", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I owe my guild a great debt for forging me into the person I am today.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I pursue wealth to secure someone's love.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "One day I will return to my guild and prove that I am the greatest artisan of them all.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Nothing is more important than the other members of my hermitage, order, or association.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I entered seclusion because I loved someone I could not have.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Should my discovery come to light, it could bring ruin to the world.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My isolation gave me great insight into a great evil that only I can destroy.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will face any challenge to win the approval of my family.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My house's alliance with another noble family must be sustained at all costs.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Nothing is more important that the other members of my family.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am in love with the heir of a family that my family despises.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My loyalty to my sovereign is unwavering.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The common folk must see me as a hero of the people.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My family, clan, or tribe is the most important thing in my life, even when they are far from me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "An injury to the unspoiled wilderness of my home is an injury to me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will bring terrible wrath down on the evildoers who destroyed my homeland.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am the last of my tribe, and it is up to me to ensure their names enter legend.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I suffer awful visions of a coming disaster and will do anything to prevent it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "It is my duty to provide children to sustain my tribe.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "It is my duty to protect my students.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I work to preserve a library, university, scriptorium, or monastery.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My life's work is a series of tomes related to a specific field of lore.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I've been searching my whole life for the answer to a certain question.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I sold my soul for knowledge. I hope to do great deeds and win it back.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm loyal to my captain first, everything else second.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The ship is most important--crewmates and captains come and go.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'll always remember my first ship.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I was cheated of my fair share of the profits, and I want to get my due.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I would lay down my life for the people I served with.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My honor is my life.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Those who fight beside me are those worth dying for.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I fight for those who cannot fight for themselves.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My town or city is my home, and I'll fight to defend it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I sponsor an orphanage to keep others from enduring what I was forced to endure.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I owe my survival to another urchin who taught me to live on the streets.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I owe a debt I can never repay to the person who took pity on me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I escaped my life of poverty by robbing an important person, and I'm wanted for it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "No one else is going to have to endure the hardships I've been through.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "(local mages guild) supports my research.", instanceWeight: 1 },
  {
    category: "",
    subCategory: "",
    instance:
      "One day, I'll proudly wear the tabbard of my old order. Failing that, it will be buried with me. Until then, it remains rolled up in my shirt. The abrasions from the rough burlap a reminder that I'm to be punished.",
    instanceWeight: 1
  }
];
