import { CategorisedOption, selectValuesFromWeightedCategorisedOptions } from "../generatorUtils";

export function generateFlaw() {
  return selectValuesFromWeightedCategorisedOptions(flawOptions);
}

export const flawOptions: CategorisedOption[] = [
  { category: "Moral", subCategory: "", instance: "Greed (Avarice): I have an insatiable desire for wealth and possessions, often at the expense of others' needs.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Envy (Jealousy): I often feel resentful when others have what I perceive as better possessions, success, or qualities.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Wrath (Anger): I frequently experience intense anger and hostility, sometimes losing control.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Pride (Hubris): I tend to overestimate my abilities or importance and often dismiss others.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Lust (Licentiousness): I struggle with overwhelming and often inappropriate sexual desires.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Sloth (Idleness): I avoid exerting effort and often neglect my duties and responsibilities.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Gluttony (Excess): I habitually overindulge in pleasures or consumption, beyond what is necessary or healthy.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Deceit (Dishonesty): I often find myself lying or misleading others to get what I want.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Vengeance (Retribution): I hold grudges and seek to retaliate, often disproportionately, to right perceived wrongs.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Cruelty (Brutality): I can be deliberately harmful and enjoy causing pain or suffering to others.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Impiety (Blasphemy): I show a lack of respect towards sacred beliefs or practices, often irreverently.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Insensitivity (Callousness): I tend to be uncaring about others' feelings or hardships.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Malice (Malevolence): I have a desire to harm others or see them suffer.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Hypocrisy (Insincerity): I pretend to hold values or beliefs that I don't actually live by.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Selfishness (Egocentrism): I prioritize my own needs and desires above those of everyone else.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Betrayal (Treachery): I am not above breaking trust or being disloyal to gain personal benefit.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Manipulation (Exploitation): I often use others for my own advantage, manipulating situations to my benefit.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Irresponsibility (Carelessness): I tend to neglect my responsibilities and duties, often leading to negative consequences.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Ignorance (Unawareness): I lack knowledge or awareness in areas I probably should understand.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Cowardice (Fearfulness): I often avoid challenges or threats, even when action is necessary.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Pettiness (Triviality): I get caught up in minor issues, often making a big deal out of trivialities.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Dishonor (Disgrace): I've acted in ways that have lost me respect and honor among my peers.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Bitterness (Resentment): I hold onto anger and resentment from past slights and injuries for a long time.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Distrust (Cynicism/Suspicion): I tend to doubt others' intentions, believing people are mostly self-serving.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Ingratitude (Unthankfulness): I often fail to appreciate what others have done for me.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Ruthlessness (Mercilessness): I am willing to achieve my goals by any means, without pity or compassion.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Contempt (Derision): I often view others with disdain, feeling they are inferior or unworthy.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Stubbornness (Inflexibility): Once I make up my mind, I rarely change it, even in the face of new information.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Rashness (Impulsiveness/Recklessness): I act without thinking things through, often leading to unnecessary risks or problems.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Power Hunger (Ambition): I have a strong desire for power and control, and I'm driven to attain it.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Scheming (Machination): I often plot or scheme to get what I want, even if it means deceiving others.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Abusiveness (Violence): I can be physically or emotionally abusive, using force or cruelty.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Intolerance (Bigotry): I'm often unwilling to accept views or people different from myself.", instanceWeight: 1 },
  { category: "Moral", subCategory: "", instance: "Disloyalty (Unfaithfulness): I struggle with staying faithful or loyal, especially when my interests are at stake.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Paranoia (Distrust): I often can't shake the feeling that people are watching me or plotting against me.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Arrogance (Superiority): I tend to believe I am superior to others, and I dismiss those who challenge me.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Impulsiveness (Hastiness): I act on my immediate desires without considering the consequences.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Melancholy (Sadness): I am frequently enveloped by deep sadness and find little joy in life.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Obsession (Compulsion): I fixate on things intensely, sometimes to the detriment of my well-being.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Anxiety (Worry): I am constantly plagued by worries and fears that interfere with my daily life.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Delusion (Misbelief): I hold onto certain beliefs despite clear evidence that contradicts them.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Narcissism (Self-Admiration): I am preoccupied with myself and lack empathy for others.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Inferiority Complex (Self-Doubt): I feel chronically inadequate and often see myself as less than others.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Phobia (Irrational Fear): I have irrational fears that control and limit my life in significant ways.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Megalomania (Delusions of Grandeur): I have an inflated sense of my own importance and a deep need for admiration.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Masochism (Pain Gratification): I derive a sense of pleasure when I endure pain or humiliation.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Sadism (Cruelty): I feel a surge of empowerment when I inflict pain or dominate others.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Mistrust (Wariness): I find it hard to trust, always suspecting people of having hidden agendas.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Dependence (Reliance): I rely too much on others to meet my emotional or physical needs.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Indecision (Hesitation): I am paralyzed when faced with decisions and often defer to others' choices.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Resentment (Bitterness): I harbor long-term feelings of bitterness towards those who I think have wronged me.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Pessimism (Negativity): I expect the worst in most situations and doubt positive outcomes.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Apathy (Indifference): I lack motivation and interest, and I'm indifferent to things that excite others.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Overconfidence (Self-Assurance): I often overestimate my own abilities and take on more than I can handle.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Mood Swings (Emotional Instability): My emotional states can change dramatically and unpredictably.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Stubbornness (Obstinacy): I am resistant to changing my viewpoint, even when presented with new evidence.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Insecurity (Uncertainty): I frequently doubt my value and question my worth.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Escapism (Avoidance): I retreat into my own world to avoid the unpleasant realities of life.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Volatility (Explosiveness): My emotional reactions are intense and can be quite sudden.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Denial (Refusal of Reality): I refuse to acknowledge unpleasant truths about myself or my life.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Jealousy (Envy): I feel threatened and uneasy when someone has something I desire.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Egocentrism (Self-Centeredness): I struggle to understand or appreciate the perspectives of others.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Fatalism (Defeatism): I believe that the course of my life is predetermined and beyond my control.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Rigidity (Inflexibility): I stick to my routines and ideas, even when they're no longer effective.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Cynicism (Distrustfulness): I doubt the goodness of others and expect people to act in self-interest.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Suspicion (Doubt): I am often skeptical of others' motives and question their intentions.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Intolerance (Unacceptance): I am dismissive of opinions and lifestyles that differ from my own.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Despair (Hopelessness): I feel a profound sense of hopelessness and see no possibility for change.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Overthinking (Analysis Paralysis): I analyze things excessively, which often prevents me from taking action.", instanceWeight: 1 },
  { category: "Psychological", subCategory: "", instance: "Defeatism (Resignation): I feel resigned to failure, as if my efforts are futile.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Disrespect (Rudeness): I often disregard others' feelings and express myself in a manner that is rude and offensive.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Arrogance (Haughtiness): I have an inflated sense of my own importance and abilities, often belittling others.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Conformity (Peer Pressure): I am easily swayed by others' opinions and tend to conform to what others do or believe, even if it's against my principles.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Antagonism (Hostility): I frequently exhibit unfriendly and aggressive behavior towards others.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Aloofness (Detachment): I remain emotionally distant and indifferent in social situations, making it hard for others to connect with me.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Gossip (Slander): I habitually spread rumors or talk about the private affairs of others.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Unreliability (Flakiness): I often fail to keep my promises or commitments, leaving others disappointed or in difficult situations.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Cynicism (Skepticism): I generally see the worst in people and situations, often expressing my skepticism and negative opinions.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Ingratitude (Unthankfulness): I rarely acknowledge or appreciate the help and kindness others offer me.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Dismissiveness (Indifference): I tend to ignore or trivialize other people's opinions, feelings, or needs.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Invasiveness (Intrusiveness): I disregard others' boundaries and privacy, often involving myself in matters where I'm not welcome.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Impatience (Restlessness): I get easily irritated and can't tolerate waiting or slow progress in others.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Overbearingness (Domineering): I tend to control or dictate how others should act or think.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Insularity (Narrow-mindedness): I am not open to new ideas or people different from myself, often rejecting anything unfamiliar.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Pessimism (Negativity): I have a tendency to see the negative side of every situation and express my pessimistic outlook, bringing down those around me.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Sarcasm (Cutting Humor): I frequently use sarcasm in a way that can be hurtful or offensive, even if it's not my intention.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Nonchalance (Apathy): I show little interest or concern for things that others find important or worrying.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Competitiveness (Rivalry): I always need to win or be the best, often at the expense of others.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Vanity (Self-Absorption): I am excessively focused on my appearance and achievements, often seeking admiration from others.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Defensiveness (Sensitivity): I quickly take offense and get defensive, even over minor criticisms or jokes.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Exhibitionism (Attention-Seeking): I constantly seek attention and often behave dramatically or inappropriately to ensure I am noticed.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Indiscretion (Tactlessness): I often speak or act without considering the feelings or circumstances of others, leading to awkward or hurtful situations.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Pride (Hubris): I have an excessive sense of self-esteem and superiority, making it difficult to acknowledge my faults or learn from others.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Suspicion (Distrust): I find it hard to trust others, often suspecting their motives or fearing betrayal.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Withdrawal (Isolation): I tend to isolate myself, avoiding social interactions and not participating in group activities.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Envy (Jealousy): I often feel resentful when others have what I perceive as better possessions, success, or qualities.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Dependence (Clinginess): I excessively rely on others for emotional support, approval, or companionship.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Intolerance (Bigotry): I am often intolerant of people who are different from me, whether in beliefs, culture, or lifestyle.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Passive-Aggression (Indirect Hostility): I express my anger and frustration in indirect and underhanded ways rather than confronting issues openly.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Moodiness (Temperamental): My mood changes unpredictably, affecting my social interactions and how I treat others.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Bluntness (Abruptness): I often speak in a very direct, sometimes harsh manner, without considering the impact of my words.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Egocentrism (Selfishness): I focus primarily on my own needs and concerns, often overlooking or dismissing the needs of others.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Mischievousness (Prankishness): I enjoy playing pranks or making jokes at others' expense, sometimes causing unintended harm or offense.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Fanaticism (Zealotry): I am overly passionate about my beliefs or interests, often pushing them onto others in an aggressive manner.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Superficiality (Shallowness): I am often concerned with surface-level aspects of social interactions, neglecting deeper or more meaningful connections.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Inflexibility (Stubbornness): I am unwilling to change my opinions or ways, even in the face of new information or in social negotiations.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Mistrust (Suspicion): I find it difficult to trust others, often doubting their intentions or honesty.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Provocation (Agitation): I tend to provoke or stir up trouble in social situations, often enjoying the chaos or conflict that ensues.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Neglect (Inattentiveness): I often neglect my relationships, failing to give time or attention to those who care about me.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Insecurity (Self-Doubt): I frequently feel insecure, leading me to act in needy or defensive ways in social interactions.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Over-sharing (Indiscretion): I have a tendency to share too much personal information, making others uncomfortable or breaching social norms.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Disorganization (Scatterbrained): I often come across as disorganized or absent-minded, affecting my reliability in social commitments.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Sarcasm (Snarkiness): I use sarcasm frequently, which can be perceived as hurtful or insensitive, even if it's intended in jest.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Pride (Vanity): I am overly proud and often boast about my achievements or qualities, sometimes alienating others.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Indifference (Aloofness): I display a lack of interest or concern for the feelings or problems of others, often appearing cold or detached.",
    instanceWeight: 1
  },
  {
    category: "Social",
    subCategory: "",
    instance: "Impulsiveness (Rashness): I act on impulse without considering the social consequences, often leading to regrettable situations.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Exaggeration (Overstatement): I have a tendency to exaggerate or embellish stories, which can mislead or alienate others.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Pessimism (Cynicism): I often have a negative or cynical view of people and situations, which can be off-putting to others.", instanceWeight: 1 },
  { category: "Social", subCategory: "", instance: "Overcritical (Judgmental): I tend to be overly critical of others, focusing on their faults rather than their strengths.", instanceWeight: 1 },
  {
    category: "Social",
    subCategory: "",
    instance: "Unpredictability (Capriciousness): My behavior in social settings is often unpredictable or erratic, making it hard for others to understand or relate to me.",
    instanceWeight: 1
  },
  { category: "Social", subCategory: "", instance: "Manipulativeness (Exploitation): I tend to manipulate others for my own benefit, often at their expense.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Poor Eyesight (Myopia): I struggle with nearsightedness, making it difficult to see objects at a distance without corrective lenses.",
    instanceWeight: 1
  },
  {
    category: "Physical",
    subCategory: "",
    instance: "Hearing Impairment (Deafness): I have limited or no hearing ability, which challenges my communication and awareness in many environments.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Chronic Pain (Fibromyalgia): I experience constant pain that limits my physical activities and affects my daily life.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Limited Mobility (Paralysis): Due to paralysis, my mobility is significantly restricted, affecting my independence and physical capabilities.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Respiratory Issues (Asthma): I suffer from asthma, which can suddenly restrict my breathing and physical exertion.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Muscular Weakness (Myopathy): My muscles are weak, making it hard to perform tasks that require strength.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Speech Impediment (Stuttering): I have a stutter, which affects my speech and makes communication challenging.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Poor Balance (Vertigo): I frequently experience dizziness and a lack of balance, making it hard to move confidently.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Amputation (Limb Loss): I have lost a limb, which significantly alters how I interact with the physical world.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Skin Condition (Eczema): I have eczema, causing skin irritation and self-consciousness about my appearance.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Allergies (Severe Allergic Reactions): I have severe allergies that can be triggered by various environmental factors, posing a constant health risk.",
    instanceWeight: 1
  },
  {
    category: "Physical",
    subCategory: "",
    instance: "Digestive Issues (Irritable Bowel Syndrome): My life is regularly disrupted by digestive problems, affecting my diet and comfort.",
    instanceWeight: 1
  },
  {
    category: "Physical",
    subCategory: "",
    instance: "Cardiac Weakness (Heart Disease): I have a heart condition that limits my physical exertion and requires constant monitoring.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Endocrine Disorders (Diabetes): I manage diabetes, which affects my diet, energy levels, and overall health.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Skeletal Deformities (Scoliosis): My spine is curved, causing me pain and affecting my posture and movement.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Neurological Disorder (Epilepsy): I have epilepsy, which means I'm susceptible to seizures, affecting my daily life and safety.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Joint Problems (Arthritis): Arthritis affects my joints, limiting my mobility and causing persistent pain.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Dental Issues (Chronic Toothache): I suffer from ongoing dental problems, affecting my eating and self-esteem.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Visual Distortions (Color Blindness): I cannot differentiate certain colors, which affects my perception and certain activities.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Lack of Stamina (Chronic Fatigue Syndrome): I deal with chronic fatigue, drastically limiting my energy for daily tasks.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Frailty (Osteoporosis): My bones are fragile, making me prone to fractures and limiting physical activities.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Migraines (Chronic Headaches): I regularly suffer from debilitating migraines, impacting my ability to function.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Sleep Disorders (Insomnia): My inability to sleep properly affects my energy levels and mental focus.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Hypersensitivity (Sensory Processing Disorder): I am overly sensitive to sensory input, which can be overwhelming and disorienting.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Impaired Coordination (Ataxia): I struggle with coordination, affecting my precision and ability to perform physical tasks.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Involuntary Movements (Tremors): I have tremors that make it difficult to maintain steadiness in my hands and body.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Breathing Difficulty (COPD): Chronic obstructive pulmonary disease limits my lung function and endurance.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Growth Disorders (Dwarfism): My growth is significantly less than average, affecting my physical capabilities and social interactions.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Obesity (Weight Issues): I struggle with obesity, which impacts my mobility, health, and self-esteem.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Underweight (Malnutrition): Being significantly underweight, I face health issues and physical weakness.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Burns (Scarring): I have severe burns that have left scars, affecting my appearance and physical sensations.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Limb Deformity (Clubfoot): A deformity in my foot affects my walk and balance, limiting my mobility.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Poor Hand-Eye Coordination (Dyspraxia): I struggle with hand-eye coordination, affecting activities that require precision.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Metabolic Issues (Hypothyroidism): My thyroid condition affects my metabolism, energy levels, and weight.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Blood Disorders (Hemophilia): I have a blood disorder that affects my clotting, posing risks with injuries.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Hormonal Imbalance (PCOS): Hormonal issues due to PCOS affect various aspects of my health and appearance.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Cleft Lip/Palate (Facial Deformity): A cleft lip affects my speech and facial appearance.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Lactose Intolerance (Dietary Restriction): I cannot digest lactose, which limits my diet and can cause discomfort.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Infertility (Reproductive Issues): I face challenges with infertility, affecting my personal and social life.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Cancer Survivor (Post-Treatment Weakness): Post-cancer treatment, I face ongoing health challenges and physical weakness.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Sensory Impairment (Tinnitus): I have persistent ringing in my ears, affecting my hearing and concentration.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Chronic Infections (Recurrent Illness): I am prone to frequent infections, affecting my health and daily activities.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Autoimmune Disorder (Lupus): My immune system attacks my body, causing various health issues and fatigue.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Cognitive Impairment (Brain Injury): A brain injury has left me with cognitive challenges, affecting my memory and thinking.",
    instanceWeight: 1
  },
  { category: "Physical", subCategory: "", instance: "Bone Frailty (Brittle Bone Disease): I have unusually fragile bones, making me vulnerable to fractures.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Gait Abnormality (Limp): An irregularity in my walk affects my mobility and endurance.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Kidney Disease (Renal Failure): Kidney disease affects my overall health and requires constant management.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Liver Disease (Hepatitis): Liver problems impact my overall health and can limit my lifestyle.", instanceWeight: 1 },
  { category: "Physical", subCategory: "", instance: "Hormone Deficiency (Growth Hormone Deficiency): A lack of growth hormone affects my physical development and health.", instanceWeight: 1 },
  {
    category: "Physical",
    subCategory: "",
    instance: "Adrenal Insufficiency (Addison's Disease): I have a condition affecting my adrenal glands, influencing my energy, mood, and health.",
    instanceWeight: 1
  },
  {
    category: "Emotional",
    subCategory: "",
    instance: "Impulsivity (Rashness): I often act on my immediate emotions without thinking about the consequences, leading to regrettable decisions.",
    instanceWeight: 1
  },
  {
    category: "Emotional",
    subCategory: "",
    instance: "Over-Sensitivity (Fragility): I am extremely sensitive to criticism or perceived slights, often feeling hurt or upset easily.",
    instanceWeight: 1
  },
  { category: "Emotional", subCategory: "", instance: "Anger Issues (Temper): I struggle to control my anger, frequently losing my temper in inappropriate ways.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Emotional Detachment (Aloofness): I find it hard to connect emotionally with others, often appearing distant or uncaring.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Mood Swings (Instability): My emotions fluctuate wildly, affecting my behavior and making me unpredictable.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Jealousy (Envy): I often feel intense jealousy, resenting others for their successes or relationships.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Anxiety (Worry): I am constantly anxious and worried, often about things that are beyond my control.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Indifference (Apathy): I lack interest or enthusiasm in things that others find important, often seeming disinterested.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Depression (Despondency): I frequently feel overwhelmed by sadness or hopelessness, impacting my daily functioning.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Lack of Empathy (Insensitivity): I struggle to understand or share the feelings of others, often appearing callous.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Pessimism (Cynicism): I tend to see the worst in situations and people, expecting negative outcomes.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Insecurity (Self-Doubt): I often feel inadequate or unworthy, affecting my interactions and decisions.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Guilt (Remorsefulness): I am frequently consumed by guilt, even for things outside my control.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Fearfulness (Timidity): I am often excessively fearful or timid, avoiding risks or challenges.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Defensiveness (Guardedness): I quickly become defensive in response to criticism or questioning.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Vulnerability (Fragileness): I am easily hurt or affected by external influences, often feeling vulnerable.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Obsessiveness (Fixation): I tend to fixate on certain thoughts or ideas, unable to let them go.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Paranoia (Distrust): I often feel paranoid, suspecting others of deceit or harm without evidence.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Narcissism (Egotism): I am overly focused on myself and my own importance, disregarding others.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Histrionics (Dramatic): I tend to be overly dramatic and emotional, often seeking attention.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Overwhelm (Stress): I easily get overwhelmed by emotions, making it hard to cope with stress.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Stubbornness (Inflexibility): I am often unreasonably stubborn, refusing to change my emotional stance.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Resentment (Bitterness): I harbor deep resentment towards certain people or experiences.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Impatience (Restlessness): I am often impatient, finding it hard to wait or cope with delays.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Indecisiveness (Hesitancy): I struggle to make decisions, often fluctuating between emotions and choices.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Disappointment (Dissatisfaction): I am frequently disappointed with people and situations, leading to dissatisfaction.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Passivity (Submissiveness): I tend to be overly passive, suppressing my emotions to avoid conflict.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Euphoria (Overexcitement): I sometimes experience intense, unrealistic euphoria that skews my judgment.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Regret (Remorse): I am often plagued by regret over past actions or decisions.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Misery (Unhappiness): I frequently feel a deep sense of misery or unhappiness.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Contempt (Scorn): I often feel contemptuous, looking down on others or situations.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Over-Attachment (Clinginess): I become overly attached emotionally, which can be smothering to others.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Despair (Hopelessness): I often feel a sense of despair, seeing little hope or possibility in situations.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Over-Criticism (Judgmental): I am overly critical of myself and others, focusing on faults and mistakes.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Yearning (Longing): I have intense, often unfulfilled yearnings, which leave me feeling dissatisfied.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Shame (Humiliation): I frequently feel shame, often internalizing failures or embarrassments.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Melancholy (Sorrow): I often feel a deep, pervasive melancholy that affects my perspective.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Exhaustion (Burnout): I experience emotional exhaustion, feeling drained from coping with my feelings.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Hostility (Aggression): I often exhibit hostility, reacting aggressively in emotional situations.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Nostalgia (Yearning for the Past): I am excessively nostalgic, often lost in longing for the past.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Disdain (Contempt): I feel disdain towards others or situations, often dismissing them outright.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Ingratitude (Unthankfulness): I often fail to feel or express gratitude, taking things for granted.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Revengefulness (Vindictiveness): I harbor a desire for revenge, holding onto grudges and seeking payback.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Over-Excitability (Impulsiveness): I get overly excited easily, leading to impulsive reactions.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Grief (Mourning): I am deeply grieving, which profoundly affects my emotional state and interactions.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Distrust (Suspicion): I am often distrustful, suspecting others' motives and intentions.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Over-Optimism (Naivety): I am sometimes naively over-optimistic, overlooking potential risks or downsides.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Self-Pity (Moroseness): I frequently indulge in self-pity, focusing on my own misfortunes.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Discontent (Restlessness): I am often discontented, feeling restless and unsatisfied with my situation.", instanceWeight: 1 },
  { category: "Emotional", subCategory: "", instance: "Fanaticism (Zealotry): I display emotional fanaticism, often going to extremes for my beliefs or passions.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Naivety (Gullibility): I tend to believe things too easily, often being misled or deceived.", instanceWeight: 1 },
  {
    category: "Intelligence",
    subCategory: "",
    instance: "Shortsightedness (Lack of Foresight): I struggle to see the long-term consequences of my actions, focusing only on immediate outcomes.",
    instanceWeight: 1
  },
  { category: "Intelligence", subCategory: "", instance: "Ignorance (Uninformed): I lack essential knowledge or awareness in areas I probably should understand.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Inattentiveness (Distractibility): I find it hard to focus, easily getting distracted from the task at hand.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Impulsiveness (Haste): I often make decisions too quickly, without fully thinking them through.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Forgetfulness (Absent-mindedness): I frequently forget important information or commitments.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Closed-mindedness (Stubbornness): I am resistant to new ideas or perspectives, stubbornly sticking to my own beliefs.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Poor Judgment (Indiscretion): I often make poor decisions, failing to consider all the factors or potential outcomes.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Curiosity (Disinterest): I have little interest in learning or exploring new things.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Illogical Thinking (Irrationality): My reasoning often lacks logic, leading me to draw flawed conclusions.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Overconfidence (Hubris): I overestimate my own knowledge or abilities, often leading to mistakes.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Misinterpretation (Misunderstanding): I frequently misunderstand information or the intentions of others.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Poor Problem-Solving (Inefficiency): I struggle to find effective solutions to problems, often making situations worse.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Intuition (Insensitivity): I fail to read between the lines or pick up on non-verbal cues.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Poor Memory (Forgetfulness): I have trouble recalling information, which affects my learning and understanding.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Rigidity (Inflexibility): I am inflexible in my thinking, struggling to adapt to new information or changes.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Superficial Understanding (Shallowness): My understanding of complex subjects is often superficial and lacking depth.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Creativity (Unimaginativeness): I find it difficult to think creatively or come up with original ideas.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Slow Learning (Difficulty Grasping Concepts): I take longer than usual to understand new concepts or skills.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Analysis (Superficiality): I tend not to analyze things deeply, missing important details or implications.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Indecisiveness (Hesitation): I struggle to make decisions, often wavering and uncertain.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Dogmatism (Rigidity): I rigidly adhere to my own beliefs, unwilling to consider alternative viewpoints.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Narrow-mindedness (Intolerance): I have a narrow view of things, unwilling to accept different ideas or opinions.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Strategic Thinking (Poor Planning): I am not good at planning ahead or strategizing, often caught unprepared.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Insight (Obliviousness): I often lack insight into situations or people, missing underlying issues.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Misjudgment (Poor Assessment): I frequently misjudge situations or people, leading to incorrect conclusions.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Conformity (Lack of Originality): I tend to follow others' thoughts or ideas, lacking originality in my thinking.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Distorted Perception (Misconception): My perception of reality is often distorted, leading me to incorrect beliefs.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Detail Orientation (Oversight): I often overlook details, focusing only on the bigger picture.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Incoherence (Scatterbrained): My thoughts are often disorganized, making it hard to articulate them clearly.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Fantasy-Prone (Daydreaming): I get lost in fantasies and daydreams, losing touch with reality.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Credulity (Blind Belief): I am too quick to believe things without questioning their validity.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Simplistic Thinking (Naiveness): My thinking is often too simplistic, not appreciating the complexity of situations.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Irresponsibility (Carelessness): I am careless in my thought processes, often neglecting to consider the repercussions.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Prejudice (Bias): My thinking is clouded by prejudices, affecting my ability to be objective.", instanceWeight: 1 },
  {
    category: "Intelligence",
    subCategory: "",
    instance: "Inability to Synthesize (Fragmented Thinking): I struggle to connect different ideas or information, leading to fragmented thinking.",
    instanceWeight: 1
  },
  { category: "Intelligence", subCategory: "", instance: "Unreflective (Thoughtlessness): I seldom reflect on my experiences or beliefs, lacking self-awareness.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Miscalculation (Error in Judgment): I often miscalculate or misjudge situations, leading to errors in my decisions.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Unwillingness to Learn (Stubbornness): I am often unwilling to learn new things or adapt my understanding.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Selective Memory (Bias): I remember things selectively, often in a way that confirms my existing beliefs.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Literal-mindedness (Inability to Grasp Nuances): I tend to take things literally, missing nuances or implied meanings.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Overgeneralization (Sweeping Statements): I make broad generalizations without sufficient evidence.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Disorganization (Muddled Thinking): My thoughts are often disorganized, leading to confusion and inefficiency.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Compulsive Fixation (Obsession): I become compulsively fixated on certain ideas, unable to let them go.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Lack of Reflection (Unthoughtfulness): I don't spend time reflecting on my experiences or ideas.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Jumping to Conclusions (Hasty Generalization): I often jump to conclusions without adequate information or reasoning.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Reductive Reasoning (Oversimplification): I oversimplify complex issues, reducing them to basic, often flawed, terms.", instanceWeight: 1 },
  { category: "Intelligence", subCategory: "", instance: "Projection (Blaming Others): I project my own thoughts or feelings onto others, misinterpreting their actions.", instanceWeight: 1 },
  {
    category: "Intelligence",
    subCategory: "",
    instance: "Inability to Prioritize (Poor Focus): I struggle to prioritize information or tasks, leading to ineffective decision-making.",
    instanceWeight: 1
  },
  { category: "Intelligence", subCategory: "", instance: "Denial (Refusal to Accept Reality): I often deny reality, refusing to accept facts that contradict my beliefs.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Dogmatism (Rigidity): I rigidly adhere to my beliefs, refusing to consider alternative viewpoints or evidence.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Superstition (Irrational Beliefs): I hold onto irrational beliefs and superstitions, even when they're proven baseless.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Cynicism (Distrust): I generally view people and situations with distrust and skepticism, expecting the worst.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Prejudice (Bias): I harbor unfair prejudices against certain groups or beliefs, affecting my judgment and actions.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Fatalism (Resignation): I believe that fate controls everything and that my actions have little impact.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Paranoia (Suspicion): I am overly suspicious and often believe in elaborate conspiracies without proof.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Nihilism (Pessimism): I believe that life is meaningless and reject all religious and moral principles.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Idealism (Naivety): My beliefs are overly idealistic and not grounded in reality, leading to disappointment.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Fanaticism (Zealotry): I am excessively zealous about my beliefs, often to the point of extremism.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Moral Relativism (Ethical Ambiguity): I believe that morality is subjective, often using it to justify questionable actions.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Narcissism (Self-Centeredness): I hold an inflated view of my own importance and believe I am above others.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Hedonism (Pleasure-seeking): I believe in pursuing pleasure as the highest good, often at the expense of others.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Pessimism (Hopelessness): I have a pessimistic view of the world, often feeling that things will inevitably go wrong.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Materialism (Greed): I place excessive value on material possessions and wealth.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Chauvinism (Superiority): I believe in the superiority of my own group, whether national, political, or social.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Apathy (Indifference): I am indifferent to social, political, or ethical issues, showing little concern or interest.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Skepticism (Doubt): I am excessively skeptical, often questioning the validity of widely accepted truths or beliefs.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Blind Faith (Gullibility): I accept beliefs blindly, without questioning or seeking evidence.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Xenophobia (Fear of Outsiders): I irrationally fear and distrust people from other countries or cultures.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Entitlement (Self-importance): I believe that I am inherently deserving of privileges or special treatment.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Obsession (Compulsion): I am obsessed with certain ideas or beliefs, often to an unhealthy degree.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Dependence (Reliance): I overly rely on certain beliefs or systems, unable to think or act independently.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Defeatism (Pessimism): I hold a defeatist attitude, believing that failure is inevitable and unavoidable.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Escapism (Avoidance): I use beliefs or fantasies to escape from reality or responsibilities.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Moral Superiority (Judgmental): I believe in my moral superiority, often judging others harshly.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Misogyny (Sexism): I hold prejudiced beliefs against women, viewing them as inferior or lesser.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Racism (Bigotry): I harbor racist beliefs, considering certain races or ethnicities to be superior or inferior.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Homophobia (Intolerance): I have an irrational fear or dislike of homosexual individuals.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Religious Extremism (Fundamentalism): I hold extreme religious views, often rejecting any differing beliefs.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Conformity (Compliance): I tend to conform blindly to societal or group beliefs without question.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Egotism (Self-obsession): I am overly focused on myself, often disregarding the perspectives or needs of others.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Black-and-White Thinking (Simplistic): I see things in absolute terms, with no room for complexity or nuance.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Over-Generalization (Stereotyping): I often make broad generalizations about groups or situations.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Antisocial Beliefs (Rebellion): I hold beliefs that go against societal norms, sometimes leading to harmful actions.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Misanthropy (Hatred of Humankind): I have a general hatred or distrust of humankind.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Irresponsibility (Carelessness): I believe that I am not responsible for my actions or their consequences.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Disillusionment (Cynicism): I am deeply disillusioned with certain ideals or beliefs I once held.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Vulnerability (Susceptibility): I am easily influenced or hurt by the beliefs or opinions of others.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Traditionalism (Conventionalism): I strictly adhere to traditional beliefs, often resisting change or new ideas.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Machismo (Hypermasculinity): I believe in and exhibit exaggerated masculine traits or behaviors.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Inflexibility (Rigidity): I am inflexible in my beliefs, unwilling to adapt or reconsider them.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Elitism (Snobbery): I believe that I belong to an elite group, deserving special status or privileges.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Cultural Ignorance (Insensitivity): I am ignorant of or insensitive to other cultures and their beliefs.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Resentment (Bitterness): I hold deep-seated resentment towards certain beliefs or groups.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Isolationism (Detachment): I believe in isolating myself or my group from the wider world or different ideas.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Passivity (Submissiveness): I am overly passive in my beliefs, often accepting what I am told without question.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Radicalism (Extremism): I hold radical beliefs, advocating for drastic political or social changes.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Disregard for Authority (Rebellion): I have a blatant disregard for authority or established beliefs.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Ageism (Generational Bias): I hold prejudiced beliefs against individuals of certain age groups.", instanceWeight: 1 },
  { category: "Belief", subCategory: "", instance: "Classism (Elitism): I believe in the superiority of certain social or economic classes over others.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Incompetence (Lack of Skill): I lack the necessary skills or knowledge for my job, often failing to meet standards.",
    instanceWeight: 1
  },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Unreliability (Irresponsibility): I am known to be unreliable, frequently missing deadlines or failing to complete tasks.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Procrastination (Delaying): I habitually procrastinate, often leaving tasks until the last minute.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Indifference (Apathy): I show little interest or enthusiasm in my work, doing the bare minimum required.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Unethical Behavior (Dishonesty): I often engage in unethical practices at work, such as lying or cutting corners.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Poor Leadership (Ineffectiveness): As a leader, I struggle to motivate or effectively manage my team.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Mismanagement (Inefficiency): I am not good at managing resources or people, often leading to chaos or waste.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Lack of Initiative (Passivity): I rarely take initiative, usually waiting to be told what to do.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Overbearing (Domineering): I tend to be overbearing, micromanaging or controlling every aspect of work.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Negligence (Carelessness): I am often negligent, overlooking important details that affect my work quality.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Lack of Communication (Withholding): I fail to communicate effectively, often leading to misunderstandings or confusion.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Resistant to Change (Stubbornness): I resist new ideas or ways of working, preferring to stick to the old ways.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Conflict Avoidance (Passiveness): I avoid addressing conflicts, often letting issues fester unresolved.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Poor Teamwork (Non-Collaborative): I struggle to work well in a team, often causing friction or disunity.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Lack of Adaptability (Inflexibility): I am not adaptable, struggling with changes or new demands in my profession.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Lack of Ambition (Complacency): I lack ambition, content with mediocrity rather than striving for excellence.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Manipulativeness (Exploitation): I tend to manipulate others for my own benefit, often at their expense.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Credit Stealing (Dishonesty): I often take credit for others' work or ideas, ignoring their contributions.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Unprofessionalism (Inappropriateness): I frequently behave inappropriately, disregarding professional norms or etiquette.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Impulsiveness (Rashness): I make hasty decisions without fully considering the consequences.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Defensiveness (Non-Receptive): I am overly defensive to feedback or criticism, rarely taking it constructively.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Insubordination (Disobedience): I often defy orders or guidelines, preferring to do things my own way.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Burnout (Exhaustion): I am experiencing burnout, affecting my performance and motivation.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Cynicism (Skepticism): I am overly cynical about my job and colleagues, which affects my attitude and work.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Over-Competitiveness (Rivalry): I am excessively competitive, often at the expense of teamwork or ethics.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Lack of Confidence (Self-Doubt): I lack confidence in my abilities, often second-guessing myself.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Absenteeism (Frequent Absences): I am frequently absent from work, causing disruptions and extra burdens for others.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Micromanagement (Over-Control): I micromanage everything, not trusting my team to work independently.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Lack of Professional Growth (Stagnation): I show little interest in professional development or learning new skills.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Arrogance (Egotism): I am arrogant about my abilities, often overestimating my competence.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Tardiness (Lateness): I am regularly late, showing disrespect for others' time and commitments.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Blame Shifting (Deflecting): I tend to shift blame to others, avoiding taking responsibility for my mistakes.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Lack of Enthusiasm (Disinterest): I show little enthusiasm for my work, doing only what is necessary.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Isolationism (Non-Participation): I isolate myself, not engaging with colleagues or participating in team activities.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Disharmony (Conflict Creation): I often create or escalate conflicts, disrupting workplace harmony.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Pessimism (Negativity): I am overly pessimistic, often demoralizing others with my negative outlook.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Gossiping (Rumor Spreading): I indulge in gossip, spreading rumors or confidential information.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Bullying (Intimidation): I engage in workplace bullying, intimidating or belittling my colleagues.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Close-mindedness (Rigidity): I am close-minded, unwilling to consider new ideas or perspectives.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Lack of Empathy (Insensitive): I show little empathy towards colleagues, often disregarding their feelings or challenges.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Disorganization (Messiness): I am disorganized, often mismanaging my time and resources.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Avoidance (Evasion): I tend to avoid difficult tasks or decisions, leaving them to others.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Undermining (Sabotage): I sometimes undermine colleagues, intentionally or unintentionally sabotaging their work.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Distractibility (Inattentiveness): I am easily distracted, finding it hard to concentrate on my work.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Lack of Creativity (Unimaginativeness): I lack creativity, often sticking to outdated methods or ideas.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Exaggeration (Overstatement): I tend to exaggerate my achievements or capabilities, often misleading others.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Over-dependence (Reliance): I rely too heavily on others, not taking enough responsibility for my work.", instanceWeight: 1 },
  { category: "Professional Conduct", subCategory: "", instance: "Disrespect (Rudeness): I am often disrespectful to colleagues or clients, showing a lack of professionalism.", instanceWeight: 1 },
  {
    category: "Professional Conduct",
    subCategory: "",
    instance: "Lack of Transparency (Secretiveness): I am not transparent in my dealings, often keeping information or intentions hidden.",
    instanceWeight: 1
  },
  { category: "Professional Conduct", subCategory: "", instance: "Overworking (Workaholism): I tend to overwork, neglecting personal life and potentially burning out.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Greed (Avarice): I have an insatiable desire for wealth and possessions, often at the expense of others' needs.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Envy (Jealousy): I often feel resentful when others have what I perceive as better possessions, success, or qualities.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Wrath (Anger): I frequently experience intense anger and hostility, sometimes losing control.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Pride (Hubris): I tend to overestimate my abilities or importance and often dismiss others.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Lust (Licentiousness): I struggle with overwhelming and often inappropriate sexual desires.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Sloth (Idleness): I avoid exerting effort and often neglect my duties and responsibilities.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Gluttony (Excess): I habitually overindulge in pleasures or consumption, beyond what is necessary or healthy.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Deceit (Dishonesty): I often find myself lying or misleading others to get what I want.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Vengeance (Retribution): I hold grudges and seek to retaliate, often disproportionately, to right perceived wrongs.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Cruelty (Brutality): I can be deliberately harmful and enjoy causing pain or suffering to others.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Impiety (Blasphemy): I show a lack of respect towards sacred beliefs or practices, often irreverently.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Insensitivity (Callousness): I tend to be uncaring about others' feelings or hardships.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Malice (Malevolence): I have a desire to harm others or see them suffer.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Hypocrisy (Insincerity): I pretend to hold values or beliefs that I don't actually live by.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Selfishness (Egocentrism): I prioritize my own needs and desires above those of everyone else.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Betrayal (Treachery): I am not above breaking trust or being disloyal to gain personal benefit.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Manipulation (Exploitation): I often use others for my own advantage, manipulating situations to my benefit.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Irresponsibility (Carelessness): I tend to neglect my responsibilities and duties, often leading to negative consequences.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Ignorance (Unawareness): I lack knowledge or awareness in areas I probably should understand.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Obsession (Fixation): I have an unhealthy obsession, often neglecting other aspects of my life.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Addiction (Dependency): I am addicted to substances or activities, which dominate my life and decisions.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Narcissism (Self-Obsession): I am excessively focused on myself, often neglecting or using others.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Spite (Vindictiveness): I act out of spite, seeking to hurt or upset others for perceived slights.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Paranoia (Distrust): I am overly suspicious or paranoid, often seeing malice where there is none.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Fanaticism (Obsessive Zeal): I am fanatical about my beliefs or passions, often to an unhealthy degree.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Indulgence (Excess): I indulge excessively in comforts or luxuries, often at the expense of my well-being.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Impulsiveness (Recklessness): I act on impulses without considering the consequences, often resulting in harm.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Cowardice (Fearfulness): I often let fear dictate my actions, avoiding risks or challenges.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Arrogance (Haughtiness): I am overly arrogant, belittling others and overestimating my own importance.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Procrastination (Laziness): I habitually procrastinate, avoiding tasks or responsibilities.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Cynicism (Distrustfulness): I am cynically distrustful of people's motives and intentions.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Despair (Hopelessness): I often succumb to feelings of despair and hopelessness.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Judgmentalism (Criticism): I am overly critical of others, often judging them harshly and unfairly.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Defensiveness (Guardedness): I react defensively to feedback or criticism, often refusing to change.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Ingratitude (Unthankfulness): I fail to show gratitude, often taking others and their efforts for granted.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Intolerance (Bigotry): I am intolerant of differences, often rejecting or disparaging those unlike me.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Dishonesty (Deception): I habitually lie or deceive others for my own gain or convenience.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Stubbornness (Inflexibility): I am unreasonably stubborn, refusing to change my opinion or course of action.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Overbearingness (Domineering): I am domineering in my interactions, often trying to control others.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Impatience (Restlessness): I am frequently impatient, easily irritated by delays or waiting.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Moodiness (Temperamental): My mood swings affect my interactions, often leading to conflicts or hurt.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Pettiness (Triviality): I often focus on petty issues, making mountains out of molehills.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Evasiveness (Elusiveness): I am evasive, often avoiding direct answers or responsibilities.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Vulgarity (Coarseness): I often display vulgar or coarse behavior, disregarding social norms.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Unforgiving (Resentfulness): I struggle to forgive, often holding onto grudges and resentments.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Disrespect (Rudeness): I frequently act disrespectfully towards others, disregarding their feelings or dignity.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Rashness (Haste): I make hasty decisions without fully considering the implications.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Pessimism (Negativity): I have a pessimistic outlook, often expecting the worst in situations.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Sarcasm (Biting Wit): I use sarcasm frequently, which can be hurtful or inappropriate.", instanceWeight: 1 },
  { category: "Vice", subCategory: "", instance: "Gossip (Rumor-Mongering): I engage in spreading gossip, often discussing others' private affairs.", instanceWeight: 1 }
];

// 1. Moral Flaws: These are ethical failings indicating a lack of or skewed moral compass. These flaws often involve actions that violate accepted ethical norms and values, leading to harm or injustice.
// 2. Psychological Flaws: These are mental or emotional issues that negatively affect a character's behavior, judgement, or ability to function.
// 3. Social Flaws: This category covers deficiencies in social interactions or relationships.
// 4. Emotional Flaws: Tied to a character's ability to manage and express their emotions in a healthy way
// 5. Physical Flaws: These are physical constraints that limit a character's abilities.
// 6. Intelligence Flaws: These involve shortcomings in a character's intellect, reasoning, or knowledge.
// 7. Belief Flaws: This class of flaws relates to problematic views or principles the character holds.
// 8. Professional Conduct Flaws: These are flaws rooted in a character's performance or behavior within their occupation.
// 9. Vices: These are compulsive or habitual negative behaviors often tied to personal desires or impulses.
