import { CategorisedOption, selectValuesFromWeightedCategorisedOptions } from "../generatorUtils";

export function generateFlaw() {
  return selectValuesFromWeightedCategorisedOptions(flawOptions);
}

export const flawOptions: CategorisedOption[] = [
  { category: "", subCategory: "", instance: "I judge others harshly, and myself even more severely.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I put too much trust in those who wield power within my temple's hierarchy.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My piety sometimes leads me to blindly trust those that profess faith in my god.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am inflexible in my thinking.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am suspicious of strangers and suspect the worst of them.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I can't resist a pretty face.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm convinced that no one could ever fool me in the way I fool others.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm too greedy for my own good. I can't resist taking a risk if there's money involved.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I can't resist swindling people who are more powerful than me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "When I see something valuable, I can't think about anything but how to steal it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "When faced with a choice between money and my friends, I usually choose the money.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a 'tell' that reveals when I'm lying.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I turn tail and run when things go bad.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "An innocent person is in prison for a crime that I committed. I'm okay with that.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'll do anything to win fame and renown.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm a sucker for a pretty face.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Despite my best efforts, I am unreliable to my friends.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The tyrant who rules my land will stop at nothing to see me killed.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The people who knew me when I was young know my shameful secret, so I can never go home again.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a weakness for the vices of the city, especially hard drink.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Secretly, I believe that things would be better if I were a tyrant lording over the land.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have trouble trusting in my allies.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'll do anything to get my hands on something rare or priceless.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm quick to assume that someone is trying to cheat me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "No one must ever learn that I once stole money from guild coffers.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm never satisfied with what I have--I always want more.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I would kill to acquire a noble title.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm horribly jealous of anyone who outshines my handiwork. Everywhere I go, I'm surrounded by rivals.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Now that I've returned to the world, I enjoy its delights a little too much.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I harbor dark bloodthirsty thoughts that my isolation failed to quell.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am dogmatic in my thoughts and philosophy.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I let my need to win arguments overshadow friendships and harmony.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'd risk too much to uncover a lost bit of knowledge.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I like keeping secrets and won't share them with anyone.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I secretly believe that everyone is beneath me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I hide a truly scandalous secret that could ruin my family forever.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have an insatiable desire for carnal pleasures.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "In fact, the world does revolve around me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "By my words and actions, I often bring shame to my family.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am too enamored of ale, wine, and other intoxicants.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "There's no room for caution in a life lived to the fullest.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am slow to trust members of other races", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Violence is my answer to almost any challenge.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am easily distracted by the promise of information.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Most people scream and run when they see a demon. I stop and take notes on its anatomy.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Unlocking an ancient mystery is worth the price of a civilization.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I overlook obvious solutions in favor of complicated ones.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I speak without really thinking through my words, invariably insulting others.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I can't keep a secret to save my life, or anyone else's.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I follow orders, even if I think they're wrong.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'll say anything to avoid having to do extra work.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Once someone questions my courage, I never back down no matter how dangerous the situation.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Once I start drinking, it's hard for me to stop.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I can't help but pocket loose coins and other trinkets I come across.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My pride will probably lead to my destruction", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The monstrous enemy we faced in battle still leaves me quivering with fear.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have little respect for anyone who is not a proven warrior.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I made a terrible mistake in battle that cost many lives--and I would do anything to keep that mistake secret.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My hatred of my enemies is blind and unreasoning.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I obey the law, even if the law causes misery.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'd rather eat my armor than admit when I'm wrong.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "If I'm outnumbered, I always run away from a fight.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Gold seems like a lot of money to me, and I'll do just about anything for more of it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I will never fully trust anyone other than myself.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'd rather kill someone in their sleep than fight fair.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "It's not stealing if I need it more than someone else.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "People who don't take care of themselves get what they deserve.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Can't resist a wager.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Can't sleep (has to succeed on a saving throw to get full rest)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Guilty conscience.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Drama queen", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Showoff", instanceWeight: 1 },
  {
    category: "",
    subCategory: "",
    instance:
      "Completely ignorant about anything to do with nature or animals. Cows, horses, ducks... these are all the same animal to me, perhaps at different stages of their lifecycle. Wait, horses are the poisonous ones, right? Do they fly? No, I'm thinking of goats.",
    instanceWeight: 1
  },
  {
    category: "",
    subCategory: "",
    instance: "Has to make sure the Innkeeper in any town he goes to doesn't know him because he's been run out of nearly every town he's been to - but can't remember which one's he's been to",
    instanceWeight: 1
  },
  { category: "", subCategory: "", instance: "Has a debilitating sense of direction - Has been wandering between two forests in Cheliax thinking he's been going in circles.", instanceWeight: 1 },
  {
    category: "",
    subCategory: "",
    instance:
      'Willing to do very nasty things to gain more power as long as he can rationalize it somehow. "Its okay to torture these men. They were bandits, they deserve to suffer. I am still good. Still good..."',
    instanceWeight: 1
  },
  {
    category: "",
    subCategory: "",
    instance: "I'm unworthy, a failure. If someone must be made to suffer, I'll gladly stand their punishment. If I can be convinced to suffer for the greater good, I'll abandon my current goals.",
    instanceWeight: 1
  }
];
