import { CategorisedOption, selectValuesFromWeightedCategorisedOptions } from "../generatorUtils";

export function generateIdeal() {
  return selectValuesFromWeightedCategorisedOptions(idealOptions);
}

export const idealOptions: CategorisedOption[] = [
  { category: "", subCategory: "", instance: "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Charity. I always try to help those in need, no matter what the personal cost. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Aspiration. I seek to prove my self worthy of my god's favor by matching my actions against his or her teachings. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Independence. I am a free spirit--no one tells me what to do. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Fairness. I never target people who can't afford to lose a few coins. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Charity. I distribute money I acquire to the people who really need it. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Creativity. I never run the same con twice. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Friendship. Material goods come and go. Bonds of friendship last forever. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Aspiration. I'm determined to make something of myself. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Honor. I don't steal from others in the trade. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Charity. I steal from the wealthy so that I can help people in need. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Greed. I will do whatever it takes to become wealthy. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Redemption. There's a spark of good in everyone. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Beauty. When I perform, I make the world better than it was. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Tradition. The stories, legends, and songs of the past must never be forgotten. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Creativity. The world is in need of new ideas and bold action. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Greed. I'm only in it for the money and fame. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Respect. People deserve to be treated with dignity and respect. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Might. If I become strong, I can take what I want--what I deserve. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Sincerity. There's no good pretending to be something I'm not. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Destiny. Nothing and no one can steer me away from my higher calling. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Generosity. My talents were given to me so that I could use them to benefit the world. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Freedom. Everyone should be free to pursue his or her livelihood. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Greed. I'm only in it for the money. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "People. I'm committed to the people I care about, not to ideals. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Aspiration. I work hard to be the best there is at my craft. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Greater Good. My gifts are meant to be shared with all, not used for my own benefit. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Power. Solitude and contemplation are paths toward mystical or magical power. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Self-Knowledge. If you know yourself, there're nothing left to know. (Any)", instanceWeight: 1 },
  {
    category: "",
    subCategory: "",
    instance: "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)",
    instanceWeight: 1
  },
  { category: "", subCategory: "", instance: "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Power. If I can attain more power, no one will tell me what to do. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Family. Blood runs thicker than water. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Greater Good. It is each person's responsibility to make the most happiness for the whole tribe. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Might. The strongest are meant to rule. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Nature. The natural world is more important than all the constructs of civilization. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Glory. I must earn glory in battle, for myself and my clan. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Beauty. What is beautiful points us beyond itself toward what is true. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Logic. Emotions must not cloud our logical thinking. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Power. Knowledge is the path to power and domination. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Self-improvement. The goal of a life of study is the betterment of oneself.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Fairness. We all do the work, so we all share in the rewards. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Freedom. The sea is freedom--the freedom to go anywhere and do anything. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Master. I'm a predator, and the other ships on the sea are my prey. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "People. I'm committed to my crewmates, not to ideals. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Aspiration. Someday I'll own my own ship and chart my own destiny. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Greater Good. Our lot is to lay down our lives in defense of others. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Responsibility. I do what I must and obey just authority. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Independence. When people follow orders blindly they embrace a kind of tyranny. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Might. In life as in war, the stronger force wins. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Ideals aren't worth killing for or going to war for. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Nation. My city, nation, or people are all that matter. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Respect. All people, rich or poor, deserve respect. (Good)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Community. We have to take care of each other, because no one else is going to do it. (Lawful)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things. (Chaotic)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Retribution. The rich need to be shown what life and death are like in the gutters. (Evil)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "People. I help people who help me--that's what keeps us alive. (Neutral)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Aspiration. I'm going to prove that I'm worthy of a better life. (Any)", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "If we just shared magical knowledge between all the races, we would all be able to drink enchanted ale.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "A just and orderly society is a safe society. If I'm good enough, I can make everyone safe forever.", instanceWeight: 1 }
];
