import { CategorisedOption, selectValuesFromWeightedCategorisedOptions } from "../generatorUtils";

export function generateTrait() {
  return selectValuesFromWeightedCategorisedOptions(traitOptions);
}

export const traitOptions: CategorisedOption[] = [
  { category: "", subCategory: "", instance: "I idolize a particular hero of my faith and constantly refer to that person's deeds and example.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I see omens in every event and action. The gods try to speak to us, we just need to listen.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Nothing can shake my optimistic attitude.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I quote (or misquote) the sacred texts and proverbs in almost every situation.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I've spent so long in the temple that I have little practical experience dealing with people in the outside world.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I fall in and out of love easily, and am always pursuing someone.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a joke for every occasion, especially occasions where humor is inappropriate.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Flattery is my preferred trick for getting what I want.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm a born gambler who can't resist taking a risk for a potential payoff.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I lie about almost everything, even when there's no good reason to.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Sarcasm and insults are my weapons of choice.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I pocket anything I see that might have some value.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I always have a plan for what to do when things go wrong.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The first thing I do in a new place is note the locations of everything valuable--or where such things could be hidden.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I would rather make a new friend than a new enemy.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I don't pay attention to the risks in a situation. Never tell me the odds.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The best way to get me to do something is to tell me I can't do it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I blow up at the slightest insult.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I know a story relevant to almost every situation.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Whenever I come to a new place, I collect local rumors and spread gossip.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm a hopeless romantic, always searching for that 'special someone'.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Nobody stays angry at me or around me for long, since I can defuse any amount of tension.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I love a good insult, even one directed at me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I get bitter if I'm not the center of attention.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'll settle for nothing less than perfection.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I change my mood or my mind as quickly as I change key in a song.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I judge people by their actions, not their words.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "If someone is in trouble, I'm always willing to lend help.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "When I set my mind to something, I follow through no matter what gets in my way.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a strong sense of fair play and always try to find the most equitable solution to arguments.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm confident in my own abilities and do what I can to instill confidence in others.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Thinking is for other people. I prefer action.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I misuse long words in an attempt to sound smarter.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I get bored easily. When am I going to get on with my destiny.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I believe that everything worth doing is worth doing right. I can't help it--I'm a perfectionist.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm a snob who looks down on those who can't appreciate fine art.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I always want to know how things work and what makes people tick.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm full of witty aphorisms and have a proverb for every occasion.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm rude to people who lack my commitment to hard work and fair play.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I like to talk at length about my profession.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I don't part with my money easily and will haggle tirelessly to get the best deal possible.", instanceWeight: 1 },
  {
    category: "",
    subCategory: "",
    instance: "I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.",
    instanceWeight: 1
  },
  { category: "", subCategory: "", instance: "I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am utterly serene, even in the face of disaster.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The leader of my community has something wise to say on every topic, and I am eager to share that wisdom.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I feel tremendous empathy for all who suffer.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm oblivious to etiquette and social expectations.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I connect everything that happens to me to a grand cosmic plan.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I often get lost in my own thoughts and contemplations, becoming oblivious to my surroundings.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am working on a grand philosophical theory and love sharing my ideas.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "The common folk love me for my kindness and generosity.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I take great pains to always look my best and follow the latest fashions.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Despite my birth, I do not place myself above other folk. We all have the same blood.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My favor, once lost, is lost forever.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "If you do me an injury, I will crush you, ruin your name, and salt your fields.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm driven by a wanderlust that led me away from home.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I watch over my friends as if they were a litter of newborn pups.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I once ran twenty-five miles without stopping to warn my clan of an approaching orc horde. I'd do it again if I had to.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a lesson for every situation, drawn from observing nature.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I feel far more comfortable around animals than people.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I was, in fact, raised by wolves.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I use polysyllabic words to convey the impression of great erudition.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I've read every book in the world's greatest libraries--or like to boast that I have.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "There's nothing I like more than a good mystery.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm willing to listen to every side of an argument before I make my own judgment.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I...speak...slowly...when talking...to idiots...which...almost...everyone...is...compared ...to me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I am horribly, horribly awkward in social situations.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm convinced that people are always trying to steal my secrets.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My friends know they can rely on me, no matter what.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I work hard so that I can play hard when the work is done.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I enjoy sailing into new ports and making new friends over a flagon of ale.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I stretch the truth for the sake of a good story.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "To me, a tavern brawl is a nice way to get to know a new city.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I never pass up a friendly wager.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "My language is as foul as an otyugh nest.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I like a job well done, especially if I can convince someone else to do it.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm always polite and respectful.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm haunted by memories of war. I can't get the images of violence out of my mind.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I've lost too many friends, and I'm slow to make new ones.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I can stare down a hellhound without flinching.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I enjoy being strong and like breaking things.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I have a crude sense of humor.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I face problems head-on. A simple direct solution is the best path to success.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I hide scraps of food and trinkets away in my pockets.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I ask a lot of questions.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I like to squeeze into small places where no one else can get to me.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I eat like a pig and have bad manners.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I think anyone who's nice to me is hiding evil intent.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I don't like to bathe.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I bluntly say what other people are hinting or hiding.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Fiercely superstitious.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Uses excessive force, overkill, saving nothing for later.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Always takes credit.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Speaks only in riddles and rhymes.", instanceWeight: 1 },
  {
    category: "",
    subCategory: "",
    instance: "Spent entire upbringing indoors, obsessed with uncovering the enchantments that make elven wine so special, and applying them to human beer brewing.",
    instanceWeight: 1
  },
  { category: "", subCategory: "", instance: "Is terrified of Sky-spiders - but isn't sure they actually exist", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "He will study an opponent - learn the best strategy for defeating him, and do the exact opposite just to see what happens", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Keeps as many weapons as he can carry on him for the off chance that he drops one.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "Obsessed with being 'fair'", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm overly cautious with ethical dilemmas. If I can get it right, they will take me back.", instanceWeight: 1 },
  { category: "", subCategory: "", instance: "I'm never afraid to do what has to be done or get my hands dirty. I am reliable to the end.", instanceWeight: 1 }
];
